# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IPS2 <- function(rho, n, T, W, maxit, eps) {
    .Call('copCS_IPS2', PACKAGE = 'copCS', rho, n, T, W, maxit, eps)
}

